export function collectDomRefs(documentRef = document) {
  return {
    fields: [...documentRef.querySelectorAll("[data-field], [data-derived-field]")],
    derivedFields: [...documentRef.querySelectorAll("[data-derived-field]")],
    rangeFields: [...documentRef.querySelectorAll("[data-range-field], [data-derived-range-field]")],
    modeButtons: [...documentRef.querySelectorAll(".mode-button")],
    themeButtons: [...documentRef.querySelectorAll(".theme-button")],
    sidebarTabs: [...documentRef.querySelectorAll(".sidebar-tab")],
    sidebarPanels: [...documentRef.querySelectorAll(".sidebar-panel")],
    presetButtons: [...documentRef.querySelectorAll(".preset-button")],
    panelToggles: [...documentRef.querySelectorAll(".panel-toggle")],
    plotPanels: [...documentRef.querySelectorAll(".plot-panel[data-panel]")],
    pillTabGroups: [
      documentRef.querySelector(".sidebar-tabs"),
      ...documentRef.querySelectorAll(".segmented"),
      documentRef.querySelector(".preset-button")?.parentElement,
    ].filter(Boolean),
    projectJson: documentRef.querySelector("#projectJson"),
    importExportButton: documentRef.querySelector("#importExportButton"),
    importExportDialog: documentRef.querySelector("#importExportDialog"),
    closeImportExportDialog: documentRef.querySelector("#closeImportExportDialog"),
    importJsonButton: documentRef.querySelector("#importJsonButton"),
    projectDialogStatus: documentRef.querySelector("#projectDialogStatus"),
    driverSearchInput: documentRef.querySelector("#driverSearchInput"),
    driverSearchButton: documentRef.querySelector("#driverSearchButton"),
    driverSearchStatus: documentRef.querySelector("#driverSearchStatus"),
    driverSearchResults: documentRef.querySelector("#driverSearchResults"),
    driverHealthPanel: documentRef.querySelector("#driverHealthPanel"),
    driverSelect: documentRef.querySelector("#driverSelect"),
    driverLibraryFilter: documentRef.querySelector("#driverLibraryFilter"),
    driverLibrarySort: documentRef.querySelector("#driverLibrarySort"),
    driverLibraryFilterEnabled: documentRef.querySelector("#driverLibraryFilterEnabled"),
    driverLibraryBrand: documentRef.querySelector("#driverLibraryBrand"),
    driverLibraryDiameter: documentRef.querySelector("#driverLibraryDiameter"),
    driverGroupList: documentRef.querySelector("#driverGroupList"),
    addDriverGroupButton: documentRef.querySelector("#addDriverGroupButton"),
    passiveRadiatorSelect: documentRef.querySelector("#passiveRadiatorSelect"),
    passiveRadiatorLibraryFilter: documentRef.querySelector("#passiveRadiatorLibraryFilter"),
    passiveRadiatorLibrarySort: documentRef.querySelector("#passiveRadiatorLibrarySort"),
    passiveRadiatorLibraryFilterEnabled: documentRef.querySelector("#passiveRadiatorLibraryFilterEnabled"),
    passiveRadiatorLibraryBrand: documentRef.querySelector("#passiveRadiatorLibraryBrand"),
    passiveRadiatorLibraryDiameter: documentRef.querySelector("#passiveRadiatorLibraryDiameter"),
    passiveRadiatorSearchInput: documentRef.querySelector("#passiveRadiatorSearchInput"),
    passiveRadiatorSearchButton: documentRef.querySelector("#passiveRadiatorSearchButton"),
    passiveRadiatorSearchStatus: documentRef.querySelector("#passiveRadiatorSearchStatus"),
    passiveRadiatorSearchResults: documentRef.querySelector("#passiveRadiatorSearchResults"),
    planDesignsButton: documentRef.querySelector("#planDesignsButton"),
    plannerStatus: documentRef.querySelector("#plannerStatus"),
    plannerResults: documentRef.querySelector("#plannerResults"),
    crossoverGroupSelect: documentRef.querySelector("#crossoverGroupSelect"),
    crossoverMemberList: documentRef.querySelector("#crossoverMemberList"),
    crossoverStatus: documentRef.querySelector("#crossoverStatus"),
    signalFilterTypeSelect: documentRef.querySelector("#signalFilterTypeSelect"),
    signalFilterAddButton: documentRef.querySelector("#signalFilterAddButton"),
    signalFilterList: documentRef.querySelector("#signalFilterList"),
    configGroupList: documentRef.querySelector("#configGroupList"),
    configBarList: documentRef.querySelector("#configBarList"),
    newConfigButton: documentRef.querySelector("#newConfigButton"),
    newConfigGroupButton: documentRef.querySelector("#newConfigGroupButton"),
  };
}
