export function collectDomRefs(documentRef = document) {
  return {
    fields: [...documentRef.querySelectorAll("[data-field], [data-derived-field]")],
    derivedFields: [...documentRef.querySelectorAll("[data-derived-field]")],
    rangeFields: [...documentRef.querySelectorAll("[data-range-field], [data-derived-range-field]")],
    modeButtons: [...documentRef.querySelectorAll(".mode-button")],
    themeButtons: [...documentRef.querySelectorAll(".theme-button")],
    sidebarTabs: [...documentRef.querySelectorAll(".sidebar-tab")],
    sidebarPanels: [...documentRef.querySelectorAll(".sidebar-panel")],
    panelToggles: [...documentRef.querySelectorAll(".panel-toggle")],
    plotPanels: [...documentRef.querySelectorAll(".plot-panel[data-panel]")],
    pillTabGroups: [
      documentRef.querySelector(".sidebar-tabs"),
      ...documentRef.querySelectorAll(".segmented"),
    ].filter(Boolean),
    projectJson: documentRef.querySelector("#projectJson"),
    importExportButton: documentRef.querySelector("#importExportButton"),
    importExportDialog: documentRef.querySelector("#importExportDialog"),
    closeImportExportDialog: documentRef.querySelector("#closeImportExportDialog"),
    fileSaveButton: documentRef.querySelector("#fileSaveButton"),
    fileOpenButton: documentRef.querySelector("#fileOpenButton"),
    exportButton: documentRef.querySelector("#exportButton"),
    importInput: documentRef.querySelector("#importInput"),
    importJsonButton: documentRef.querySelector("#importJsonButton"),
    projectDialogStatus: documentRef.querySelector("#projectDialogStatus"),
    driverSearchInput: documentRef.querySelector("#driverSearchInput"),
    driverSearchButton: documentRef.querySelector("#driverSearchButton"),
    driverSearchStatus: documentRef.querySelector("#driverSearchStatus"),
    driverUsageSummary: documentRef.querySelector("#driverUsageSummary"),
    driverValidationDetails: documentRef.querySelector("#driverValidationDetails"),
    driverValidationStatus: documentRef.querySelector("#driverValidationStatus"),
    driverSelect: documentRef.querySelector("#driverSelect"),
    driverLibraryFilter: documentRef.querySelector("#driverLibraryFilter"),
    driverLibrarySort: documentRef.querySelector("#driverLibrarySort"),
    driverLibraryFilterEnabled: documentRef.querySelector("#driverLibraryFilterEnabled"),
    driverLibraryBrand: documentRef.querySelector("#driverLibraryBrand"),
    driverLibraryDiameter: documentRef.querySelector("#driverLibraryDiameter"),
    driverGroupList: documentRef.querySelector("#driverGroupList"),
    addDriverGroupButton: documentRef.querySelector("#addDriverGroupButton"),
    passiveRadiatorSelect: documentRef.querySelector("#passiveRadiatorSelect"),
    passiveRadiatorLibraryFilter: documentRef.querySelector("#passiveRadiatorLibraryFilter"),
    passiveRadiatorLibrarySort: documentRef.querySelector("#passiveRadiatorLibrarySort"),
    passiveRadiatorLibraryFilterEnabled: documentRef.querySelector("#passiveRadiatorLibraryFilterEnabled"),
    passiveRadiatorLibraryBrand: documentRef.querySelector("#passiveRadiatorLibraryBrand"),
    passiveRadiatorLibraryDiameter: documentRef.querySelector("#passiveRadiatorLibraryDiameter"),
    passiveRadiatorSearchInput: documentRef.querySelector("#passiveRadiatorSearchInput"),
    passiveRadiatorSearchButton: documentRef.querySelector("#passiveRadiatorSearchButton"),
    passiveRadiatorSearchStatus: documentRef.querySelector("#passiveRadiatorSearchStatus"),
    crossoverStatus: documentRef.querySelector("#crossoverStatus"),
    signalFilterTypeSelect: documentRef.querySelector("#signalFilterTypeSelect"),
    signalFilterAddButton: documentRef.querySelector("#signalFilterAddButton"),
    crossoverSchematicBoard: documentRef.querySelector("#crossoverSchematicBoard"),
    measurementPlaneSelect: documentRef.querySelector("#measurementPlaneSelect"),
    measurementTargetSelect: documentRef.querySelector("#measurementTargetSelect"),
    frequencyResponseInput: documentRef.querySelector("#frequencyResponseInput"),
    measurementStatus: documentRef.querySelector("#measurementStatus"),
    measurementList: documentRef.querySelector("#measurementList"),
    recordingMicrophoneSelect: documentRef.querySelector("#recordingMicrophoneSelect"),
    recordingOutputSelect: documentRef.querySelector("#recordingOutputSelect"),
    recordingSignalSelect: documentRef.querySelector("#recordingSignalSelect"),
    recordingFrequencyStartInput: documentRef.querySelector("#recordingFrequencyStartInput"),
    recordingFrequencyEndInput: documentRef.querySelector("#recordingFrequencyEndInput"),
    recordingLevelInput: documentRef.querySelector("#recordingLevelInput"),
    recordingDurationInput: documentRef.querySelector("#recordingDurationInput"),
    recordingAveragingInput: documentRef.querySelector("#recordingAveragingInput"),
    recordingSampleRateSelect: documentRef.querySelector("#recordingSampleRateSelect"),
    recordingTestToneButton: documentRef.querySelector("#recordingTestToneButton"),
    recordingAddButton: documentRef.querySelector("#recordingAddButton"),
    recordingRunNameInput: documentRef.querySelector("#recordingRunNameInput"),
    recordingRunAngleInput: documentRef.querySelector("#recordingRunAngleInput"),
    recordingSaveRunButton: documentRef.querySelector("#recordingSaveRunButton"),
    recordingStatus: documentRef.querySelector("#recordingStatus"),
    recordingLevelReadout: documentRef.querySelector("#recordingLevelReadout"),
    recordingSpectrogram: documentRef.querySelector("#recordingSpectrogram"),
    recordingPeakReadout: documentRef.querySelector("#recordingPeakReadout"),
    recordingMeterBar: documentRef.querySelector("#recordingMeterBar"),
    configBarList: documentRef.querySelector("#configBarList"),
    newConfigButton: documentRef.querySelector("#newConfigButton"),
    newConfigGroupButton: documentRef.querySelector("#newConfigGroupButton"),
    configAddMenu: documentRef.querySelector("#configAddMenu"),
    mobileNewConfigButton: documentRef.querySelector("#mobileNewConfigButton"),
    mobileNewConfigGroupButton: documentRef.querySelector("#mobileNewConfigGroupButton"),
  };
}
