import { scrapeDriverPage } from "./driverScraper.js";
import { fetchUrl as fetch } from "./fetch.js";
import { analyzeDriverParameters, deriveDriverParameters } from "./driver.js";

const SITEMAP_URL = "https://www.parts-express.com/sitemap_pages.xml";
const REQUEST_DELAY_MS = 180;
const DRIVER_TERMS = /(woofer|subwoofer|driver|tweeter|midrange|full-range|fullrange|coaxial|speaker-driver|compression-driver)/i;
const EXCLUDE_TERMS = /(amplifier|stand|mount|cable|adapter|connector|microphone|headphone|earbud|grill|grille|horn-|waveguide|replacement|kit|package|bundle|cabinet|enclosure|crossover|terminal|binding-post|foam|surround|passive-radiator|radiator|manual|bracket|plate|rack|case|battery|charger|receiver|transmitter)/i;
const REQUIRED_FIELDS = ["re", "fs", "qms", "qes", "vasL", "sdCm2", "xmaxMm", "mmsG", "bl"];

export async function findPartsExpressDriverUrls() {
  const xml = await fetch(SITEMAP_URL).then((response) => {
    if (!response.ok) throw new Error(`Parts Express sitemap HTTP ${response.status}`);
    return response.text();
  });
  const urls = [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((match) => decodeXml(match[1]));
  return [...new Set(urls)].filter(isDriverCandidateUrl);
}

export async function scrapePartsExpressDrivers(options = {}) {
  const {
    limit = Number.POSITIVE_INFINITY,
    offset = 0,
    concurrency = 4,
    minFields = 6,
    onProgress = () => {},
  } = options;

  const allCandidates = await findPartsExpressDriverUrls();
  const candidates = allCandidates.slice(offset, Number.isFinite(limit) ? offset + limit : undefined);
  const drivers = [];
  const failures = [];
  let cursor = 0;
  let scanned = 0;

  async function worker() {
    while (cursor < candidates.length) {
      const index = cursor;
      cursor += 1;
      const url = candidates[index];
      await delay(REQUEST_DELAY_MS);
      try {
        const result = await scrapeDriverPage(url, { title: titleFromUrl(url) });
        scanned += 1;
        if (isUsableDriver(result, minFields)) {
          drivers.push(toDriverEntry(result));
        }
        onProgress({ scanned, matched: drivers.length, total: candidates.length, url });
      } catch (error) {
        scanned += 1;
        failures.push({ url, error: error.message || "Failed" });
        onProgress({ scanned, matched: drivers.length, total: candidates.length, url, error: error.message });
      }
    }
  }

  await Promise.all(Array.from({ length: Math.max(1, concurrency) }, worker));

  return {
    source: "parts-express",
    generatedAt: new Date().toISOString(),
    totalCandidateUrls: allCandidates.length,
    scanned,
    matched: drivers.length,
    failures: failures.length,
    drivers: dedupeDrivers(drivers).sort((a, b) => a.name.localeCompare(b.name)),
  };
}

export function serializeDriverModule(importResult) {
  return `// Generated by scripts/import-parts-express.mjs. Do not edit by hand.\nexport const partsExpressDrivers = ${JSON.stringify(importResult.drivers, null, 2)};\nexport const partsExpressImportMeta = ${JSON.stringify(
    {
      source: importResult.source,
      generatedAt: importResult.generatedAt,
      totalCandidateUrls: importResult.totalCandidateUrls,
      scanned: importResult.scanned,
      matched: importResult.matched,
      failures: importResult.failures,
    },
    null,
    2,
  )};\n`;
}

function isDriverCandidateUrl(url) {
  return url.includes("parts-express.com/") && DRIVER_TERMS.test(url) && !EXCLUDE_TERMS.test(url);
}

function isUsableDriver(result, minFields) {
  const driver = normalizeImportedDriver(result.driver);
  const keys = Object.keys(driver);
  const hasRequiredFields = REQUIRED_FIELDS.every((field) => Number.isFinite(driver[field]) && driver[field] > 0);
  const hasWarnings = analyzeDriverParameters(driver).issues.some((issue) => issue.severity === "warning");
  return keys.length >= minFields && hasRequiredFields && !hasWarnings;
}

function toDriverEntry(result) {
  return {
    id: `parts-express-${productCodeFromUrl(result.url) || slugify(result.title)}`,
    name: cleanTitle(result.title),
    source: result.url,
    driver: normalizeImportedDriver(result.driver),
    matched: result.matched,
  };
}

function normalizeImportedDriver(input = {}) {
  const driver = { ...input };
  const areaWasSquareMeters = driver.sdCm2 > 0 && driver.sdCm2 < 1;
  if (areaWasSquareMeters) driver.sdCm2 = roundValue(driver.sdCm2 * 10000);
  if (driver.mmsG > 0 && driver.mmsG < 1 && shouldTreatMassAsKg(driver, areaWasSquareMeters)) {
    driver.mmsG = roundValue(driver.mmsG * 1000);
  }
  if (driver.leMh > 20) driver.leMh = roundValue(driver.leMh / 1000);

  const completed = deriveDriverParameters(driver);
  if (!driver.mmsG && Number.isFinite(completed.mmsG) && completed.mmsG > 0) {
    driver.mmsG = completed.mmsG;
  }
  if (!driver.bl && Number.isFinite(completed.bl) && completed.bl > 0) {
    driver.bl = completed.bl;
  }
  return driver;
}

function shouldTreatMassAsKg(driver, areaWasSquareMeters) {
  if (areaWasSquareMeters) return true;
  const derivedMms = analyzeDriverParameters(driver).derived.mmsG;
  if (!Number.isFinite(derivedMms) || derivedMms <= 0) return false;
  const gramError = relativeError(driver.mmsG, derivedMms);
  const kgError = relativeError(driver.mmsG * 1000, derivedMms);
  return kgError < 0.25 && gramError > 2;
}

function relativeError(actual, expected) {
  return Math.abs(expected - actual) / Math.max(Math.abs(actual), 1e-9);
}

function roundValue(value) {
  if (Math.abs(value) >= 100) return Math.round(value * 10) / 10;
  if (Math.abs(value) >= 10) return Math.round(value * 100) / 100;
  return Math.round(value * 1000) / 1000;
}

function dedupeDrivers(drivers) {
  const seen = new Map();
  for (const driver of drivers) {
    seen.set(driver.id, driver);
  }
  return [...seen.values()];
}

function titleFromUrl(url) {
  const slug = url.split("/").pop() || url;
  return decodeURIComponent(slug)
    .replace(/-\d{3}-\d+$/, "")
    .replace(/-/g, " ");
}

function cleanTitle(title) {
  return String(title || "")
    .replace(/\s*-\s*Parts Express.*$/i, "")
    .replace(/\s*\|\s*Parts Express.*$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function productCodeFromUrl(url) {
  const match = String(url).match(/(\d{3}-\d+)(?:$|[/?#])/);
  return match?.[1]?.replace("-", "");
}

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 80);
}

function decodeXml(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
