import { scrapePassiveRadiatorPage } from "./driverScraper.js";

const SITEMAP_URL = "https://www.parts-express.com/sitemap_pages.xml";
const REQUEST_DELAY_MS = 180;
const PASSIVE_RADIATOR_TERMS = /passive-radiator/i;
const EXCLUDE_TERMS = /(category|what-is|speaker-components\/|kit|package|bundle|replacement|foam|surround|ring-radiator|tweeter|bass-radiator)/i;
const REQUIRED_FIELDS = ["fs", "mmsG", "sdCm2"];

export async function findPartsExpressPassiveRadiatorUrls() {
  const xml = await fetch(SITEMAP_URL).then((response) => {
    if (!response.ok) throw new Error(`Parts Express sitemap HTTP ${response.status}`);
    return response.text();
  });
  const urls = [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((match) => decodeXml(match[1]));
  return [...new Set(urls)].filter(isPassiveRadiatorCandidateUrl);
}

export async function scrapePartsExpressPassiveRadiators(options = {}) {
  const { concurrency = 4, onProgress = () => {} } = options;
  const candidates = await findPartsExpressPassiveRadiatorUrls();
  const passiveRadiators = [];
  const failures = [];
  let cursor = 0;
  let scanned = 0;

  async function worker() {
    while (cursor < candidates.length) {
      const index = cursor;
      cursor += 1;
      const url = candidates[index];
      await delay(REQUEST_DELAY_MS);
      try {
        const result = await scrapePassiveRadiatorPage(url, { title: titleFromUrl(url) });
        scanned += 1;
        if (isUsablePassiveRadiator(result)) {
          passiveRadiators.push(toPassiveRadiatorEntry(result));
        }
        onProgress({ scanned, matched: passiveRadiators.length, total: candidates.length, url });
      } catch (error) {
        scanned += 1;
        failures.push({ url, error: error.message || "Failed" });
        onProgress({ scanned, matched: passiveRadiators.length, total: candidates.length, url, error: error.message });
      }
    }
  }

  await Promise.all(Array.from({ length: Math.max(1, concurrency) }, worker));

  return {
    source: "parts-express-passive-radiators",
    generatedAt: new Date().toISOString(),
    totalCandidateUrls: candidates.length,
    scanned,
    matched: passiveRadiators.length,
    failures: failures.length,
    passiveRadiators: dedupe(passiveRadiators).sort((a, b) => a.name.localeCompare(b.name)),
  };
}

export function serializePassiveRadiatorModule(importResult) {
  return `// Generated by scripts/import-passive-radiators.mjs. Do not edit by hand.\nexport const passiveRadiators = ${JSON.stringify(importResult.passiveRadiators, null, 2)};\nexport const passiveRadiatorImportMeta = ${JSON.stringify(
    {
      source: importResult.source,
      generatedAt: importResult.generatedAt,
      totalCandidateUrls: importResult.totalCandidateUrls,
      scanned: importResult.scanned,
      matched: importResult.matched,
      failures: importResult.failures,
    },
    null,
    2,
  )};\n`;
}

function isPassiveRadiatorCandidateUrl(url) {
  return url.includes("parts-express.com/") && PASSIVE_RADIATOR_TERMS.test(url) && !EXCLUDE_TERMS.test(url);
}

function isUsablePassiveRadiator(result) {
  return REQUIRED_FIELDS.every((field) => Number.isFinite(result.passiveRadiator[field]));
}

function toPassiveRadiatorEntry(result) {
  return {
    id: `parts-express-pr-${productCodeFromUrl(result.url) || slugify(result.title)}`,
    name: cleanTitle(result.title),
    source: result.url,
    passiveRadiator: {
      qms: 7,
      xmaxMm: 10,
      ...result.passiveRadiator,
    },
    matched: result.matched,
  };
}

function dedupe(passiveRadiators) {
  const seen = new Map();
  for (const passiveRadiator of passiveRadiators) {
    seen.set(passiveRadiator.id, passiveRadiator);
  }
  return [...seen.values()];
}

function titleFromUrl(url) {
  const slug = url.split("/").pop() || url;
  return decodeURIComponent(slug)
    .replace(/-\d{3}-\d+$/, "")
    .replace(/-/g, " ");
}

function cleanTitle(title) {
  return String(title || "")
    .replace(/\s*-\s*Parts Express.*$/i, "")
    .replace(/\s*\|\s*Parts Express.*$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function productCodeFromUrl(url) {
  const match = String(url).match(/(\d{3}-\d+)(?:$|[/?#])/);
  return match?.[1]?.replace("-", "");
}

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 80);
}

function decodeXml(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
